export const GET_TRACKNAME_REQUEST = 'GET_TRACKNAME_REQUEST'
export const GET_TRACKNAME_SUCCESS = 'GET_TRACKNAME_SUCCESS'
export const GET_TRACKNAME_FAILURE = 'GET_TRACKNAME_FAILURE'

export const GET_ART_URL_REQUEST = 'GET_ART_URL_REQUEST'
export const GET_ART_URL_SUCCESS = 'GET_ART_URL_SUCCESS'
export const GET_ART_URL_FAILURE = 'GET_ART_URL_FAILURE'

export const GET_STATUS_REQUEST = 'GET_STATUS_REQUEST'
export const GET_STATUS_SUCCESS = 'GET_STATUS_SUCCESS'
export const GET_STATUS_FAILURE = 'GET_STATUS_FAILURE'
